version: '3.9'

services:
  web:
    image: monyorojoseph/escrownest-web:latest
    container_name: escrownest-web
    restart: always
    ports:
      - "3000:6969"
    env_file:
      - .web.env
  
  app:
    image: monyorojoseph/escrownest-app:latest
    container_name: escrownest-app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .app.env