# Generated by Django 5.1.5 on 2025-02-21 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentagreement',
            old_name='days_to_deliver',
            new_name='holding_days',
        ),
    ]
