# Generated by Django 5.1.5 on 2025-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentagreement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
