# Generated by Django 5.1.5 on 2025-02-08 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paymentagreement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentagreement',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='UserVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=7, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
