# Generated by Django 5.1.5 on 2025-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paymentagreement_options_userverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverificationtoken',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
