# Generated by Django 5.1.5 on 2025-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userverificationtoken_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentagreement',
            name='currency',
            field=models.CharField(default='KES', max_length=100),
        ),
    ]
