name: Deploy

on:
    push: 
      branches: [ master ]
    workflow_dispatch:

jobs:
    test-web:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v4
              
            - name: Install Node js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install Packages and Build
              working-directory: web
              run: npm install && npm run build

    test-app:
      runs-on: ubuntu-latest      
      steps:
          - name: Checkout 
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Install requirements
            working-directory: app
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run Migrations and Tests
            working-directory: app
            run: |
              python manage.py migrate
              python manage.py test

          - name: Run Server and Quit
            working-directory: app
            run: python manage.py runserver &

    build-web:
        runs-on: ubuntu-latest
        needs: test-web
        steps:
            - name: Build Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}    

            - name: Build Image and Push
              run: |
                docker build -t escrownet-web -f docker/vite/Dockerfile web 
                docker tag escrownet-web:latest monyorojoseph/escrownet-web:latest
                docker push monyorojoseph/escrownet-web:latest

    build-app:
        runs-on: ubuntu-latest
        needs: test-app
        steps:
            - name: Build Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}    

            - name: Build Image and Push
              run: |
                docker build -t escrownet-app -f docker/Django/Dockerfile app
                docker tag escrownet-app:latest monyorojoseph/escrownet-app:latest
                docker push monyorojoseph/escrownet-app:latest  

    
    deploy:
      runs-on: ubuntu-latest
      needs: [build-web, build-app]
      steps:
          - name: Deploy Web App
            uses: D3rHase/ssh-command-action@latest
            with:
              host: ${{ secrets.HOST }}
              port: ${{ secrets.PORT }}
              user: ${{ secrets.USER }}
              private_key: ${{ secrets.PRIVATE_KEY }}
              host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
              command: |
                  "cd escrownet/ && docker compose pull && docker compose up --build -d"


